package com.mycompany.compilador3;
/**
 *
 * @author Gabriel
 */
public enum TokenType {
    IDENT, INTCONST , MENOR, MENORIGUAL, MAIOR, MAIORIGUAL, 
    PARABERTO, PARFECHADO, PONTOVIRG, TIPO, IGUAL, ATRIBUIR, DIFERENTE,
    SOMAR, SUBTRAIR, MULTIPLICAR, DIVIDIR, CHAVEABERTA, CHAVEFECHADA,
    COLCHETEABERTO, COLCHETEFECHADO, WHILE, IF, ELSE, RETURN; 
}
