Algoritmo "Dia da Semana"

Var
num: inteiro


Inicio
escreva("Escreva um número de 1 a 7: ")
leia(num)
escolha(num)
caso 1
escreva("Hoje é domingo")
caso 2
escreva("Hoje é segunda")
caso 3
escreva("Hoje é terça")
caso 4
escreva("Hoje é quarta")
caso 5
escreva("Hoje é quinta")
caso 6
escreva("Hoje é sexta")
caso 7
escreva("Hoje é sábado")
outrocaso
escreva("VALOR INVÁLIDO")
fimescolha

Fimalgoritmo