Algoritmo "Dias da Semana"

Var
dia: inteiro

Inicio
escreva("Escreva um número de 1 a 7: ")
leia(dia)
se dia = 1 então
escreva("Hoje é domingo")
fimse
se dia = 2 então
escreva("Hoje é segunda")
fimse
se dia = 3 então
escreva("Hoje é terça")
fimse
se dia = 4 então
escreva("Hoje é quarta")
fimse
se dia = 5 então
escreva("Hoje é quinta")
fimse
se dia = 6 então
escreva("Hoje é sexta")
fimse
se dia = 7 então
escreva("Hoje é sábado")
fimse
Fimalgoritmo